#ifndef PHANTOM_PROTOCOL_H
#define PHANTOM_PROTOCOL_H

#include <windows.h>

#define PHANTOM_DEVICE_NAME L"\\Device\\PhantomInject"
#define PHANTOM_SYMLINK_NAME L"\\DosDevices\\PhantomInject"
#define PHANTOM_USER_PATH L"\\\\.\\PhantomInject"

#define PHANTOM_IOCTL_MAGIC 0x8000

#define IOCTL_FIND_PROCESS \
    CTL_CODE(PHANTOM_IOCTL_MAGIC, 0x800, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IOCTL_ALLOCATE_MEMORY \
    CTL_CODE(PHANTOM_IOCTL_MAGIC, 0x801, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IOCTL_WRITE_MEMORY \
    CTL_CODE(PHANTOM_IOCTL_MAGIC, 0x802, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IOCTL_QUEUE_APC \
    CTL_CODE(PHANTOM_IOCTL_MAGIC, 0x803, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IOCTL_WIPE_HEADER \
    CTL_CODE(PHANTOM_IOCTL_MAGIC, 0x804, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IOCTL_PROTECT_MEMORY \
    CTL_CODE(PHANTOM_IOCTL_MAGIC, 0x805, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IOCTL_GET_PROCESS_BASE \
    CTL_CODE(PHANTOM_IOCTL_MAGIC, 0x806, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

typedef struct _FIND_PROCESS_REQUEST {
    WCHAR ProcessName[256];
} FIND_PROCESS_REQUEST, *PFIND_PROCESS_REQUEST;

typedef struct _FIND_PROCESS_RESPONSE {
    ULONG ProcessId;
    NTSTATUS Status;
} FIND_PROCESS_RESPONSE, *PFIND_PROCESS_RESPONSE;

typedef struct _ALLOCATE_MEMORY_REQUEST {
    ULONG ProcessId;
    ULONG_PTR Size;
    ULONG Protection;
    ULONG_PTR BaseAddress;
} ALLOCATE_MEMORY_REQUEST, *PALLOCATE_MEMORY_REQUEST;

typedef struct _ALLOCATE_MEMORY_RESPONSE {
    ULONG_PTR BaseAddress;
    NTSTATUS Status;
} ALLOCATE_MEMORY_RESPONSE, *PALLOCATE_MEMORY_RESPONSE;

typedef struct _WRITE_MEMORY_REQUEST {
    ULONG ProcessId;
    ULONG_PTR TargetAddress;
    ULONG Size;
    UCHAR Data[1];
} WRITE_MEMORY_REQUEST, *PWRITE_MEMORY_REQUEST;

typedef struct _WRITE_MEMORY_RESPONSE {
    NTSTATUS Status;
} WRITE_MEMORY_RESPONSE, *PWRITE_MEMORY_RESPONSE;

typedef struct _QUEUE_APC_REQUEST {
    ULONG ProcessId;
    ULONG ThreadId;
    ULONG_PTR ApcRoutine;
    ULONG_PTR Parameter1;
    ULONG_PTR Parameter2;
} QUEUE_APC_REQUEST, *PQUEUE_APC_REQUEST;

typedef struct _QUEUE_APC_RESPONSE {
    NTSTATUS Status;
} QUEUE_APC_RESPONSE, *PQUEUE_APC_RESPONSE;

typedef struct _WIPE_HEADER_REQUEST {
    ULONG ProcessId;
    ULONG_PTR BaseAddress;
    ULONG Size;
} WIPE_HEADER_REQUEST, *PWIPE_HEADER_REQUEST;

typedef struct _WIPE_HEADER_RESPONSE {
    NTSTATUS Status;
} WIPE_HEADER_RESPONSE, *PWIPE_HEADER_RESPONSE;

typedef struct _PROTECT_MEMORY_REQUEST {
    ULONG ProcessId;
    ULONG_PTR Address;
    ULONG Size;
    ULONG NewProtection;
    ULONG OldProtection;
} PROTECT_MEMORY_REQUEST, *PPROTECT_MEMORY_REQUEST;

typedef struct _PROTECT_MEMORY_RESPONSE {
    NTSTATUS Status;
} PROTECT_MEMORY_RESPONSE, *PPROTECT_MEMORY_RESPONSE;

typedef struct _GET_PROCESS_BASE_REQUEST {
    ULONG ProcessId;
} GET_PROCESS_BASE_REQUEST, *PGET_PROCESS_BASE_REQUEST;

typedef struct _GET_PROCESS_BASE_RESPONSE {
    ULONG_PTR BaseAddress;
    NTSTATUS Status;
} GET_PROCESS_BASE_RESPONSE, *PGET_PROCESS_BASE_RESPONSE;

#endif
