name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      - name: Build user injector
        shell: cmd
        run: msbuild user\injector\PhantomInjector.vcxproj /m /p:Configuration=Release /p:Platform=x64
      
      - name: Build user payload
        shell: cmd
        run: msbuild user\payload\PhantomClient.vcxproj /m /p:Configuration=Release /p:Platform=x64
      
      - name: Upload injector binary
        uses: actions/upload-artifact@v4
        with:
          name: PhantomInjector
          path: user/injector/x64/Release/PhantomInjector.exe
      
      - name: Upload client binary
        uses: actions/upload-artifact@v4
        with:
          name: PhantomClient
          path: user/payload/x64/Release/PhantomClient.dll
