name: Build User Injector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      - name: Build GUI Injector
        shell: cmd
        run: msbuild user\injector\PhantomInjector.vcxproj /m /p:Configuration=Release /p:Platform=x64
      
      - name: Build Cheat DLL
        shell: cmd
        run: msbuild user\cheat\PhantomCheat.vcxproj /m /p:Configuration=Release /p:Platform=x64
      
      - name: Upload injector binary
        uses: actions/upload-artifact@v4
        with:
          name: PhantomInjector
          path: user/bin/Release/PhantomInjector.exe
      
      - name: Upload cheat DLL
        uses: actions/upload-artifact@v4
        with:
          name: PhantomCheat
          path: user/bin/Release/PhantomCheat.dll
